Error happens when executing Parrot program:  <class 'requests.exceptions.JSONDecodeError'> JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback:  Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 150, in warmup
    holder = test_func("Test")
  File "/install/parrot/program/function.py", line 280, in __call__
    return self._call_func(None, *args, **kwargs)
  File "/install/parrot/program/function.py", line 325, in _call_func
    BasicFunction._virtual_machine_env.submit_call_handler(call)
  File "/install/parrot/program/vm.py", line 178, in submit_call_handler
    resp = submit_call(
  File "/install/parrot/protocol/layer_apis.py", line 78, in submit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 67, in submit_call
    return send_http_request(
  File "/install/parrot/protocol/common.py", line 39, in send_http_request
    resp_data = error_resp.json()
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

clients_num: 10
Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

{0: 0.0, 6: 0.0, 4: 0.0, 5: 0.0, 1: 0.0, 9: 0.0, 2: 0.0, 3: 0.0, 7: 0.0, 8: 0.0}
Avg. JCT 0.00 (s)
clients_num: 15
Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

{6: 0.0, 13: 0.0, 0: 0.0, 14: 0.0, 8: 0.0, 5: 0.0, 4: 0.0, 2: 0.0, 12: 0.0, 9: 0.0, 1: 0.0, 11: 0.0, 10: 0.0, 3: 0.0, 7: 0.0}
Avg. JCT 0.00 (s)
clients_num: 20
Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

{13: 0.0, 0: 0.0, 8: 0.0, 10: 0.0, 6: 0.0, 14: 0.0, 11: 0.0, 19: 0.0, 15: 0.0, 5: 0.0, 4: 0.0, 17: 0.0, 1: 0.0, 9: 0.0, 3: 0.0, 18: 0.0, 7: 0.0, 2: 0.0, 12: 0.0, 16: 0.0}
Avg. JCT 0.00 (s)
clients_num: 25
Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

Error happens when executing Parrot program:  <class 'AssertionError'> AssertionError('Send http request error: Internal Server Error')
Traceback:  Traceback (most recent call last):
  File "/install/parrot/program/vm.py", line 313, in running_scope
    yield
  File "/install/parrot/program/vm.py", line 359, in run
    loop.run_until_complete(coroutine)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/artifact/figure12b/bench_arxiv_multivm_parrot.py", line 116, in main_async
    await vm.submit_batch()
  File "/install/parrot/program/vm.py", line 217, in submit_batch
    await asyncio.gather(*self._batch)
  File "/install/parrot/program/vm.py", line 113, in _submit_call
    await asubmit_call(
  File "/install/parrot/protocol/layer_apis.py", line 98, in asubmit_call
    raise e
  File "/install/parrot/protocol/layer_apis.py", line 86, in asubmit_call
    return await async_send_http_request(
  File "/install/parrot/protocol/common.py", line 59, in async_send_http_request
    assert resp.ok, f"Send http request error: {resp.reason}"
AssertionError: Send http request error: Internal Server Error

{1: 0.0, 12: 0.0, 16: 0.0, 4: 0.0, 9: 0.0, 8: 0.0, 22: 0.0, 15: 0.0, 5: 0.0, 18: 0.0, 20: 0.0, 19: 0.0, 2: 0.0, 10: 0.0, 14: 0.0, 7: 0.0, 13: 0.0, 6: 0.0, 3: 0.0, 17: 0.0, 24: 0.0, 21: 0.0, 23: 0.0, 0: 0.0, 11: 0.0}
Avg. JCT 0.00 (s)
